version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
  - misspell
  - wsl_v5
  exclusions:
    rules:
    - path: internal
      linters:
      - wsl_v5
    - path: tests
      linters:
      - wsl_v5

formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  settings:
    gci:
      # The default order is `standard > default > custom > blank > dot > alias > localmodule`.
      custom-order: true
      sections:
      - standard
      - default
      - alias
      - localmodule
      - dot
      - blank
    gofmt:
      rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
