version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
    - bodyclose
    - dupl
    - errname
    - exhaustive
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    # - wsl_v5
  exclusions:
    rules:
      - linters:
          - gochecknoglobals
          - golint
          - gosec
          - noctx
          - scopelint
          - staticcheck
          - unparam
        path: _test\.go

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      # The default order is `standard > default > custom > blank > dot > alias > localmodule`.
      custom-order: true
      sections:
        - standard
        - default
        - alias
        - localmodule
        - dot
        - blank
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
