apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capicluster-sample
spec:
  controlPlaneRef:
    kind: K3kControlPlane
    name: capicluster-sample
  infrastructureRef:
    kind: K3kCluster
    name: capicluster-sample
