apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: K3kControlPlane
metadata:
  name: capicluster-sample
spec:
  servers: 1
  agents: 3
  token: someexamplereplaceme
  version: v1.26.0-k3s2
  serverArgs:
  - "--write-kubeconfig-mode=777"
