/*
Copyright 2024.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	clusterv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// Important: Run "make" to regenerate code after modifying this file

// K3kControlPlaneTemplateSpec defines the desired state of K3kControlPlaneTemplate
type K3kControlPlaneTemplateSpec struct {
	Template K3kControlPlaneTemplateConfig `json:"template"`
}

type K3kControlPlaneTemplateConfig struct {
	ObjectMeta clusterv1beta1.ObjectMeta `json:"metadata,omitempty"`
	Spec       K3kControlPlaneSpec       `json:"spec"`
}

// K3kControlPlaneTemplateStatus defines the observed state of K3kControlPlaneTemplate
type K3kControlPlaneTemplateStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// K3kControlPlaneTemplate is the Schema for the k3kcontrolplanetemplates API
type K3kControlPlaneTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   K3kControlPlaneTemplateSpec   `json:"spec,omitempty"`
	Status K3kControlPlaneTemplateStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// K3kControlPlaneTemplateList contains a list of K3kControlPlaneTemplate
type K3kControlPlaneTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []K3kControlPlaneTemplate `json:"items"`
}

func init() {
	SchemeBuilder.Register(&K3kControlPlaneTemplate{}, &K3kControlPlaneTemplateList{})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneTemplate) DeepCopyInto(out *K3kControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneTemplate.
func (in *K3kControlPlaneTemplate) DeepCopy() *K3kControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K3kControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneTemplateConfig) DeepCopyInto(out *K3kControlPlaneTemplateConfig) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneTemplateConfig.
func (in *K3kControlPlaneTemplateConfig) DeepCopy() *K3kControlPlaneTemplateConfig {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneTemplateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneTemplateList) DeepCopyInto(out *K3kControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K3kControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneTemplateList.
func (in *K3kControlPlaneTemplateList) DeepCopy() *K3kControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K3kControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneTemplateSpec) DeepCopyInto(out *K3kControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneTemplateSpec.
func (in *K3kControlPlaneTemplateSpec) DeepCopy() *K3kControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneTemplateStatus) DeepCopyInto(out *K3kControlPlaneTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneTemplateStatus.
func (in *K3kControlPlaneTemplateStatus) DeepCopy() *K3kControlPlaneTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
