//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/rancher/k3k/pkg/apis/k3k.io/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostKubeconfigLocation) DeepCopyInto(out *HostKubeconfigLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostKubeconfigLocation.
func (in *HostKubeconfigLocation) DeepCopy() *HostKubeconfigLocation {
	if in == nil {
		return nil
	}
	out := new(HostKubeconfigLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlane) DeepCopyInto(out *K3kControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlane.
func (in *K3kControlPlane) DeepCopy() *K3kControlPlane {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K3kControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneList) DeepCopyInto(out *K3kControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K3kControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneList.
func (in *K3kControlPlaneList) DeepCopy() *K3kControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K3kControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneSpec) DeepCopyInto(out *K3kControlPlaneSpec) {
	*out = *in
	if in.HostKubeconfig != nil {
		in, out := &in.HostKubeconfig, &out.HostKubeconfig
		*out = new(HostKubeconfigLocation)
		**out = **in
	}
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = new(int32)
		**out = **in
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = new(int32)
		**out = **in
	}
	if in.ServerArgs != nil {
		in, out := &in.ServerArgs, &out.ServerArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AgentArgs != nil {
		in, out := &in.AgentArgs, &out.AgentArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSSANs != nil {
		in, out := &in.TLSSANs, &out.TLSSANs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = make([]v1alpha1.Addon, len(*in))
		copy(*out, *in)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(v1alpha1.PersistenceConfig)
		**out = **in
	}
	if in.Expose != nil {
		in, out := &in.Expose, &out.Expose
		*out = new(v1alpha1.ExposeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneSpec.
func (in *K3kControlPlaneSpec) DeepCopy() *K3kControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K3kControlPlaneStatus) DeepCopyInto(out *K3kControlPlaneStatus) {
	*out = *in
	in.ClusterStatus.DeepCopyInto(&out.ClusterStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K3kControlPlaneStatus.
func (in *K3kControlPlaneStatus) DeepCopy() *K3kControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(K3kControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}
